/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.Enterprise.Hospital;
import Business.Network.StateNetwork;
import Business.EcoSystem;
import Business.Order.OrderRequest;
import Business.Organization.ClinicOrg;
import Business.UserAccount.UserAccount;
import Business.VaccineDirectory.VaccineList;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HarshithaApurvaNikhitha
 */
public class DoctorOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyOrdersJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    ClinicOrg clinicOrg;
    Hospital hospital;
    StateNetwork stateNetwork;
    VaccineList vaccineList;
    EcoSystem ecoSystem;
    public DoctorOrdersJPanel(JPanel userProcessContainer, UserAccount account,
                              ClinicOrg clinicOrg, Hospital hospital,
                              StateNetwork stateNetwork, VaccineList vaccineList, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.clinicOrg = clinicOrg;
        this.hospital = hospital;
        this.account = account;
        this.stateNetwork = stateNetwork;
        this.vaccineList = vaccineList;
        this.ecoSystem = ecoSystem;
        populateOrderTable();

    }
    public void populateOrderTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestTable.getModel();
        
        model.setRowCount(0);
        for (OrderRequest request : account.getOrderQueue().getOrderRequests()){
            Object[] row = new Object[7];
            row[0] = request.getVaccine().getVaccineName();
            row[1] = request;//request.getSupplier().getSupplierName()== null ? null : request.getSupplier();
            row[2] = request.getQuantity();
            row[3] = request.getOrderReceiver() == null ? null : request.getOrderReceiver().getEmployee().getEmployeeName();
            row[4] = request.getOrderStatus();
            row[5] = request.getOrderRequestDate();
            row[6] = request.getOrderResolvedDate() == null ? null : request.getOrderResolvedDate();
                       
            model.addRow(row);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestTable = new javax.swing.JTable();
        refreshTestBtn = new javax.swing.JButton();
        requestNewOrderBtn = new javax.swing.JButton();
        acceptDeliveryBtn = new javax.swing.JButton();
        trackOrderBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        orderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderLabel.setText("My Orders");
        add(orderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 780, 41));

        workRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine", "Sender", "Quantity", "Receiver", "Status", "Request Date", "Resolve Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 91, 850, 144));

        refreshTestBtn.setBackground(new java.awt.Color(153, 153, 153));
        refreshTestBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        refreshTestBtn.setText("Refresh Table");
        refreshTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestBtnActionPerformed(evt);
            }
        });
        add(refreshTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, -1, -1));

        requestNewOrderBtn.setBackground(new java.awt.Color(153, 153, 153));
        requestNewOrderBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        requestNewOrderBtn.setText("Request New Order");
        requestNewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestNewOrderBtnActionPerformed(evt);
            }
        });
        add(requestNewOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        acceptDeliveryBtn.setBackground(new java.awt.Color(153, 153, 153));
        acceptDeliveryBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        acceptDeliveryBtn.setText("Accept Delivery");
        acceptDeliveryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptDeliveryBtnActionPerformed(evt);
            }
        });
        add(acceptDeliveryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        trackOrderBtn.setBackground(new java.awt.Color(153, 153, 153));
        trackOrderBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        trackOrderBtn.setText("Track Order");
        trackOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackOrderBtnActionPerformed(evt);
            }
        });
        add(trackOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 110, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestBtnActionPerformed

        populateOrderTable();

    }//GEN-LAST:event_refreshTestBtnActionPerformed

    private void requestNewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestNewOrderBtnActionPerformed

        NewOrderJPanel requestNewOrderJPanel = new NewOrderJPanel(userProcessContainer, account, clinicOrg, stateNetwork, hospital.getPatientList(), vaccineList, this.ecoSystem);
        userProcessContainer.add("RequestNewOrderJPanel", requestNewOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_requestNewOrderBtnActionPerformed

    private void acceptDeliveryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptDeliveryBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        OrderRequest request = (OrderRequest)workRequestTable.getValueAt(selectedRow, 1);
        String status = request.getOrderStatus();
        if (status.equals("Processed by Logistics, Out for Delivery")){
        request.setOrderStatus("Delivered");
        request.getLastOrderRequest().setOrderStatus("Delivered");
        request.setResolveDate();
        request.getTransportMode().setStatus("Available");
        //clinicOrg.getInventoryDirectory().addNewItem(request.getVaccine(),request.getQuantity());
        JOptionPane.showMessageDialog(null,"Your order has been delivered !");
        }
        
        
        else{
            JOptionPane.showMessageDialog(null,"This order is not out for delivery yet !");
        }
        
        
        
       
        
        
    }//GEN-LAST:event_acceptDeliveryBtnActionPerformed

    private void trackOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackOrderBtnActionPerformed
        // TODO add your handling code here:
        
                int selectedRow = workRequestTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row !");
            return;
        }

        OrderRequest request = (OrderRequest)workRequestTable.getValueAt(selectedRow, 1);
        
        TrackMyOrdersJPanel trackOrderJPanel = new TrackMyOrdersJPanel(userProcessContainer, request);
        userProcessContainer.add("TrackOrderJPanel", trackOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
          
        
        

    }//GEN-LAST:event_trackOrderBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptDeliveryBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JButton refreshTestBtn;
    private javax.swing.JButton requestNewOrderBtn;
    private javax.swing.JButton trackOrderBtn;
    private javax.swing.JTable workRequestTable;
    // End of variables declaration//GEN-END:variables
}
