/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.Order.OrderRequest;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * @author HarshithaApurvaNikhitha
 */
public class TrackMyOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrackOrderJPanel
     */
    JPanel userProcessContainer;
    OrderRequest orderRequest;
    OrderRequest vaccineOrderRequest;

    public TrackMyOrdersJPanel(JPanel userProcessContainer, OrderRequest orderRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;

        this.orderRequest = (OrderRequest) orderRequest;

        populateData();
    }

    private void populateData() {

        if (orderRequest != null) {

            vaccineNameJLabel.setText(orderRequest.getVaccine().getVaccineName());
            vaccineQuantityJLabel.setText(String.valueOf(orderRequest.getQuantity()));
            senderJLabel.setText(orderRequest.getOrderSender().getEmployee().getEmployeeName());
            if (orderRequest.getOrderReceiver() != null) {
                receiverJLabel.setText(orderRequest.getOrderReceiver().getEmployee().getEmployeeName());
            } else {
                receiverJLabel.setText("Not Assigned yet");
            }
            if (orderRequest.getSupplier() != null) {
                supplierJLabel.setText(orderRequest.getSupplier().getSupplierName());
            }

            if (orderRequest.getTransportMode() != null) {
                etaJLabel.setText(String.valueOf(orderRequest.getETA()) + " mins");
                modeOfTransportJLabel.setText(orderRequest.getTransportMode().toString());
                distanceJLabel.setText(String.valueOf(orderRequest.getDist()) + " miles");
            } else if (orderRequest.getTransportMode() == null) {
                etaJLabel.setText("Order not dispatched yet");
                modeOfTransportJLabel.setText("N/A");
                distanceJLabel.setText("N/A");

            }


            DefaultTableModel model = (DefaultTableModel) orderLogTable.getModel();


            model.setRowCount(0);
            int i = 0;
            OrderRequest nextOrderRequest = orderRequest.createAndGetNewOrderRequest();
            while ((nextOrderRequest != null) && (nextOrderRequest.getOrderSender() != null)) {
                Object[] row = new Object[4];
                row[0] = ++i;
                row[1] = nextOrderRequest;
                row[2] = nextOrderRequest.getOrderReceiver() == null ? null : nextOrderRequest.getOrderReceiver().getEmployee().getEmployeeName();
                row[3] = nextOrderRequest.getOrderStatus();

                model.addRow(row);

                nextOrderRequest = nextOrderRequest.getOrderRequest();

            }


        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Orderlabel = new javax.swing.JLabel();
        vaccineLabel = new javax.swing.JLabel();
        vaccineNameJLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        vaccineQuantityJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderLogTable = new javax.swing.JTable();
        senderlabel = new javax.swing.JLabel();
        senderJLabel = new javax.swing.JLabel();
        receiverLabel = new javax.swing.JLabel();
        receiverJLabel = new javax.swing.JLabel();
        supplierLabel = new javax.swing.JLabel();
        supplierJLabel = new javax.swing.JLabel();
        etaJLabel = new javax.swing.JLabel();
        etaLabel = new javax.swing.JLabel();
        modeOfTransportJLabel = new javax.swing.JLabel();
        transportLabel = new javax.swing.JLabel();
        distanceJLabel = new javax.swing.JLabel();
        distanceLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));

        Orderlabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Orderlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Orderlabel.setText("Track My Order");

        vaccineLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vaccineLabel.setText("Vaccine:");

        vaccineNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vaccineNameJLabel.setText("<Vaccine Name>");

        quantityLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        quantityLabel.setText("Quantity:");

        vaccineQuantityJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vaccineQuantityJLabel.setText("<Vaccine Qty>");

        orderLogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl.no", "Sender", "Receiver", "Status"
            }
        ));
        jScrollPane1.setViewportView(orderLogTable);

        senderlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        senderlabel.setText("Sender:");

        senderJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        senderJLabel.setText("<Sender>");

        receiverLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        receiverLabel.setText("Receiver:");

        receiverJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        receiverJLabel.setText("<Receiver>");

        supplierLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        supplierLabel.setText("Supplier:");

        supplierJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supplierJLabel.setText("<Receiver>");

        etaJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etaJLabel.setText("<ETA>");

        etaLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        etaLabel.setText("ETA:");

        modeOfTransportJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modeOfTransportJLabel.setText("<MOT>");

        transportLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        transportLabel.setText("Mode of Transport:");

        distanceJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        distanceJLabel.setText("<ETA>");

        distanceLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        distanceLabel.setText("Distance:");

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(supplierLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(supplierJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(receiverLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(receiverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(senderlabel)
                                .addGap(14, 14, 14)
                                .addComponent(senderJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(transportLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(modeOfTransportJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(distanceLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(distanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vaccineLabel)
                                    .addComponent(quantityLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vaccineQuantityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vaccineNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(etaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(etaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Orderlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Orderlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etaLabel)
                        .addComponent(etaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(vaccineLabel)
                    .addComponent(vaccineNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vaccineQuantityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(senderlabel)
                            .addComponent(senderJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(receiverLabel)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(receiverJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplierLabel)
                            .addComponent(supplierJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transportLabel)
                            .addComponent(modeOfTransportJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(distanceLabel)
                            .addComponent(distanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Orderlabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel distanceJLabel;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JLabel etaJLabel;
    private javax.swing.JLabel etaLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modeOfTransportJLabel;
    private javax.swing.JTable orderLogTable;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel receiverJLabel;
    private javax.swing.JLabel receiverLabel;
    private javax.swing.JLabel senderJLabel;
    private javax.swing.JLabel senderlabel;
    private javax.swing.JLabel supplierJLabel;
    private javax.swing.JLabel supplierLabel;
    private javax.swing.JLabel transportLabel;
    private javax.swing.JLabel vaccineLabel;
    private javax.swing.JLabel vaccineNameJLabel;
    private javax.swing.JLabel vaccineQuantityJLabel;
    // End of variables declaration//GEN-END:variables
}
