/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StateHealthDeptManager;

import Business.Inventory.InventoryItem;
import Business.Organization.SupplierOrg;
import Business.UserAccount.UserAccount;
import Business.VaccineDirectory.Vaccine;
import Business.VaccineDirectory.VaccineList;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HarshithaApurvaNikhitha
 */
public class AddInventoryItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddInventoryItemJPanel
     */
    JPanel userProcessContainer;
    VaccineList vaccineList;
    SupplierOrg supplierOrg;
    UserAccount account;
    public AddInventoryItemJPanel(JPanel userProcessContainer, UserAccount account, VaccineList vaccineList, SupplierOrg supplierOrg) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.vaccineList = vaccineList;
        this.account = account;
        this.supplierOrg = supplierOrg;
        this.populateComboBox();
    }
    
    public void populateComboBox(){
        vaccineCombo.removeAllItems();
        if(vaccineList != null){
            for(Vaccine vaccine: vaccineList.getVaccineList()) {
                vaccineCombo.addItem(vaccine);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantityLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        quantitySpinner = new javax.swing.JSpinner();
        inventoryLabel = new javax.swing.JLabel();
        vaccineLabel = new javax.swing.JLabel();
        vaccineCombo = new javax.swing.JComboBox();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quantityLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        quantityLabel.setText("Quantity Available:");
        add(quantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 230, 40));

        saveBtn.setBackground(new java.awt.Color(153, 153, 153));
        saveBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        saveBtn.setText("Add Item");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 210, -1));

        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        add(quantitySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 200, 40));

        inventoryLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        inventoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventoryLabel.setText("Add Inventory Item");
        add(inventoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 580, 41));

        vaccineLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vaccineLabel.setText("Vaccine Name:");
        add(vaccineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, 40));

        vaccineCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(vaccineCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 146, 200, 40));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 110, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if(quantitySpinner.getValue().toString().matches("[A-Za-z]+")){
            JOptionPane.showMessageDialog(null, "Please enter valid quantity.");
            return;
        }
        int quantity = (int)quantitySpinner.getValue();
        Vaccine vaccine1 = (Vaccine) vaccineCombo.getSelectedItem();
        if(quantity <= 0){
            JOptionPane.showMessageDialog(null, "Please enter valid quantity.");
            return;
        }
        InventoryItem inventoryItem = this.supplierOrg.getVaccineStock().getInventoryByVaccine(vaccine1);
        if(inventoryItem == null)
            this.supplierOrg.addStock(vaccine1, quantity);
        else
            inventoryItem.setQuantity(inventoryItem.getQuantity() + quantity);
        JOptionPane.showMessageDialog(null,"Inventory Item has been added successfully !");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel inventoryLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox vaccineCombo;
    private javax.swing.JLabel vaccineLabel;
    // End of variables declaration//GEN-END:variables
}
