/*
 *To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.AdminRole;

import Business.DB4OUtilConfig.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.StateNetwork;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  Apurva
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
     private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
      private EcoSystem system;
      private UserAccount userAccount;
      private StateNetwork stateNetwork;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, StateNetwork stateNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getOrgName());
        this.userAccount = userAccount;
        this.stateNetwork = stateNetwork;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userBtn = new javax.swing.JButton();
        manageEmployeeBtn = new javax.swing.JButton();
        manageOrganizationBtn = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enterprise Administrator");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 590, -1));

        userBtn.setBackground(new java.awt.Color(153, 153, 153));
        userBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        userBtn.setText("Manage User");
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 290, 50));

        manageEmployeeBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageEmployeeBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        manageEmployeeBtn.setText("Manage Employee");
        manageEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeBtnActionPerformed(evt);
            }
        });
        add(manageEmployeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 290, 50));

        manageOrganizationBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageOrganizationBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        manageOrganizationBtn.setText("Manage Organization");
        manageOrganizationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationBtnActionPerformed(evt);
            }
        });
        add(manageOrganizationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 290, 50));

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 150, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        // TODO add your handling code here:
        UserInterface.AdministrativeRole.ManageUserAccountJPanel muajp = new UserInterface.AdministrativeRole.ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userBtnActionPerformed

    private void manageEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeBtnActionPerformed

        UserInterface.AdministrativeRole.ManageEmployeeJPanel manageEmployeeJPanel = new UserInterface.AdministrativeRole.ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationList());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeBtnActionPerformed

    private void manageOrganizationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationBtnActionPerformed

        UserInterface.AdministrativeRole.ManageOrganizationJPanel manageOrganizationJPanel = new UserInterface.AdministrativeRole.ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationList(), enterprise, userAccount, this.stateNetwork);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationBtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeeBtn;
    private javax.swing.JButton manageOrganizationBtn;
    private javax.swing.JButton userBtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
