/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClinicManager;

import Business.DiseaseList.DiseaseList;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Hospital;
import Business.Network.StateNetwork;
import Business.Organization.ClinicOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.VaccineDirectory.VaccineList;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HarshithaApurvaNikhitha
 */
public class ClinicInventoryManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryManagerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    ClinicOrg clinicOrg;
    Hospital hospital;
    StateNetwork stateNetwork;
    VaccineList vaccineList;
    DiseaseList diseaseList;
    
    public ClinicInventoryManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization clinicOrg, Enterprise hospital, StateNetwork stateNetwork, VaccineList vaccineList, DiseaseList diseaseList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.clinicOrg = (ClinicOrg) clinicOrg;
        this.hospital = (Hospital) hospital;
        this.stateNetwork = stateNetwork;
        this.vaccineList = vaccineList;
        this.diseaseList = diseaseList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InventoryLabel = new javax.swing.JLabel();
        viewInventoryBtn = new javax.swing.JButton();
        myOrdersBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InventoryLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        InventoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InventoryLabel.setText("Clinic Inventory Manager Work Area");
        add(InventoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 580, 41));

        viewInventoryBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewInventoryBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewInventoryBtn.setText("View Inventory");
        viewInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInventoryBtnActionPerformed(evt);
            }
        });
        add(viewInventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 268, 46));

        myOrdersBtn.setBackground(new java.awt.Color(153, 153, 153));
        myOrdersBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        myOrdersBtn.setText("My Orders");
        myOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myOrdersBtnActionPerformed(evt);
            }
        });
        add(myOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 268, 46));
    }// </editor-fold>//GEN-END:initComponents

    private void viewInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInventoryBtnActionPerformed
        // TODO add your handling code here:
        ViewInventoryJPanel viewInventoryJPanel = new ViewInventoryJPanel(userProcessContainer, clinicOrg.getInventoryDirectory());
        userProcessContainer.add("ViewInventoryJPanel", viewInventoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewInventoryBtnActionPerformed

    private void myOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myOrdersBtnActionPerformed
        // TODO add your handling code here:
        MyOrdersJPanel myOrdersJPanel = new MyOrdersJPanel(userProcessContainer, userAccount, clinicOrg, hospital, stateNetwork);
        userProcessContainer.add("MyOrdersJPanel", myOrdersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_myOrdersBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InventoryLabel;
    private javax.swing.JButton myOrdersBtn;
    private javax.swing.JButton viewInventoryBtn;
    // End of variables declaration//GEN-END:variables
}
