/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClinicManager;


import Business.Enterprise.SupplierEnterprise;
import Business.Network.StateNetwork;
import Business.SupplierList.Supplier;
import Business.SupplierList.VaccineInventory;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HarshithaApurvaNikhitha
 */
public class RequestNewOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestNewOrderJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    StateNetwork stateNetwork;
    public RequestNewOrderJPanel(JPanel userProcessContainer, UserAccount account, StateNetwork stateNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.stateNetwork = stateNetwork;
        loadSupplierComboBox();
    }
    
    public void loadSupplierComboBox(){
        for (SupplierEnterprise supplierEnterprise: stateNetwork.getEnterpriseList().getSupplierEnterpriseList()) {
            for(Supplier supplier: supplierEnterprise.getSupplierList().getSupplierList()){
                supplierListCombo.addItem(supplier);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReqLabel = new javax.swing.JLabel();
        supplierLabel = new javax.swing.JLabel();
        vaccineLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        supplierListCombo = new javax.swing.JComboBox();
        vaccineListCombo = new javax.swing.JComboBox();
        placeOrderBtn = new javax.swing.JButton();
        quantitySpinner = new javax.swing.JSpinner();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReqLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ReqLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReqLabel.setText("Request New Order");
        add(ReqLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 590, 41));

        supplierLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        supplierLabel.setText("Supplier:");
        add(supplierLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 40));

        vaccineLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vaccineLabel.setText("Vaccine:");
        add(vaccineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, 40));

        quantityLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        quantityLabel.setText("Quantity:");
        add(quantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 160, 40));

        supplierListCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        supplierListCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierListComboActionPerformed(evt);
            }
        });
        add(supplierListCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 210, 40));

        vaccineListCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(vaccineListCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 210, 40));

        placeOrderBtn.setBackground(new java.awt.Color(153, 153, 153));
        placeOrderBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        placeOrderBtn.setText("Place Order");
        placeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBtnActionPerformed(evt);
            }
        });
        add(placeOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 190, 50));

        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        add(quantitySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 210, 40));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBtnActionPerformed
        // TODO add your handling code here:
//<<<<<<< HEAD
//        VaccineOrderRequest request = null;
//        for(CDC hospital: stateNetwork.getEnterprises().getCDCEnterpriseList()){
//            request = hospital.getOrderQueue().addVaccineOrder();
//            
//        }
//        request.setVaccine((Vaccine)vaccineListJComboBox.getSelectedItem());
//        request.setQuantity((Integer)quantityJSpinner.getValue());
//        request.setSupplier((Supplier) supplierListJComboBox.getSelectedItem());
//        request.setOrderSender(account);
//        request.setOrderStatus("Order Sent");
//        OrderRequest lastRequest = request.getLastOrderRequest();
//        //lastRequest.createAndGetNewOrderRequest().setOrderSender(account);
//        //lastRequest.createAndGetNewOrderRequest().setOrderStatus("Order Placed");
//        JOptionPane.showMessageDialog(null,"Order placed successfully !");
//        Organization org = null;
//        account.getOrderQueue().getOrderRequests().add(request);
//=======
//        OrderRequest request = null;
//        for(CDC hospital: stateNetwork.getEnterprises().getCDCEnterpriseList()){
//            request = hospital.getOrderQueue().addOrderRequest();
//            
//        }
//        request.setVaccine((Vaccine)vaccineListJComboBox.getSelectedItem());
//        request.setQuantity((Integer)quantityJSpinner.getValue());
//        request.setSupplier((Supplier) supplierListJComboBox.getSelectedItem());
//        request.setOrderSender(account);
//        request.setOrderStatus("Order Sent");
//        OrderRequest lastRequest = request.getLastOrderRequest();
//        //lastRequest.createAndGetNewOrderRequest().setOrderSender(account);
//        //lastRequest.createAndGetNewOrderRequest().setOrderStatus("Order Placed");
//        JOptionPane.showMessageDialog(null,"Order placed successfully !");
//        Organization org = null;
//        account.getOrderQueue().getOrderRequests().add(request);
//>>>>>>> 58f625acd0eef5d03568683ad41e1c22b507c445
    }//GEN-LAST:event_placeOrderBtnActionPerformed

    private void supplierListComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierListComboActionPerformed
        // TODO add your handling code here:
        vaccineListCombo.removeAllItems();
        Supplier supplier = (Supplier)supplierListCombo.getSelectedItem();
        if(supplier!=null){
        for (VaccineInventory vaccineInventory : supplier.getVaccineInventories()) {
            vaccineListCombo.addItem(vaccineInventory.getVaccine());
        }
        }

    }//GEN-LAST:event_supplierListComboActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ReqLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton placeOrderBtn;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JLabel supplierLabel;
    private javax.swing.JComboBox supplierListCombo;
    private javax.swing.JLabel vaccineLabel;
    private javax.swing.JComboBox vaccineListCombo;
    // End of variables declaration//GEN-END:variables
}
