/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClinicManager;

//<<<<<<< HEAD
////import Business.Order.VaccineOrderRequest;
//=======

//>>>>>>> 58f625acd0eef5d03568683ad41e1c22b507c445
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HarshithaApurvaNikhitha
 */
public class TrackOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrackOrderJPanel
     */
    JPanel userProcessContainer;
//<<<<<<< HEAD
//    //VaccineOrderRequest orderRequest;
//=======
//    OrderRequest orderRequest;
//>>>>>>> 58f625acd0eef5d03568683ad41e1c22b507c445
//    
//    public TrackOrderJPanel(JPanel userProcessContainer, OrderRequest orderRequest) {
//        initComponents();
//        this.userProcessContainer = userProcessContainer;
//<<<<<<< HEAD
//        //this.orderRequest = (VaccineOrderRequest)orderRequest;
//=======
//        this.orderRequest = (OrderRequest)orderRequest;
//>>>>>>> 58f625acd0eef5d03568683ad41e1c22b507c445
//        populateData();
   // }

//    private void populateData(){
    
//        vaccineNameJLabel.setText(orderRequest.getVaccine().getCountryName());
//        vaccineQuantityJLabel.setText(String.valueOf(orderRequest.getQuantity()));
//        senderJLabel.setText(orderRequest.getOrderSender().getEmployee().getCountryName());
//        if(orderRequest.getOrderReceiver()!=null){receiverJLabel.setText(orderRequest.getOrderReceiver().getEmployee().getCountryName());}
//        
//        supplierJLabel.setText(orderRequest.getSupplier().getSupplierName());
//    DefaultTableModel model = (DefaultTableModel) orderLogJTable.getModel();
//        
//        
//            model.setRowCount(0);
//            int i=0;
//            
//            OrderRequest nextOrderRequest = orderRequest;
//            while ((nextOrderRequest!=null)&&(nextOrderRequest.getOrderSender()!=null))
//            {
//
//                Object[] row = new Object[4];
//                row[0] = ++i;
//                row[1] = nextOrderRequest.getOrderSender();
//                row[2] = nextOrderRequest.getOrderReceiver() == null ? null : nextOrderRequest.getOrderReceiver().getEmployee().getCountryName();
//                row[3] = nextOrderRequest.getOrderStatus();
//                
//                model.addRow(row);
//                
//                nextOrderRequest = nextOrderRequest.getOrderRequest();
//                
//            }
//    
//}
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trackLabel = new javax.swing.JLabel();
        vaccineLabel = new javax.swing.JLabel();
        vaccineNameLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        vaccineQuantityLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderLogTable = new javax.swing.JTable();
        senderLabel = new javax.swing.JLabel();
        senderJLabel = new javax.swing.JLabel();
        receiverLabel = new javax.swing.JLabel();
        receiverJLabel = new javax.swing.JLabel();
        supplierLabel = new javax.swing.JLabel();
        supplierJLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));

        trackLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        trackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trackLabel.setText("Track My Order");

        vaccineLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vaccineLabel.setText("Vaccine:");

        vaccineNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vaccineNameLabel.setText("<Vaccine Name>");

        quantityLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        quantityLabel.setText("Quantity:");

        vaccineQuantityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vaccineQuantityLabel.setText("<Vaccine Qty>");

        orderLogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl.no", "Sender", "Receiver", "Status"
            }
        ));
        jScrollPane1.setViewportView(orderLogTable);

        senderLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        senderLabel.setText("Sender:");

        senderJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        senderJLabel.setText("<Sender>");

        receiverLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        receiverLabel.setText("Receiver:");

        receiverJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        receiverJLabel.setText("<Receiver>");

        supplierLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        supplierLabel.setText("Supplier:");

        supplierJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supplierJLabel.setText("<Receiver>");

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(trackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quantityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vaccineQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vaccineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vaccineNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(senderLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(senderJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(supplierLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(supplierJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(receiverLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(receiverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vaccineLabel)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vaccineNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityLabel)
                    .addComponent(vaccineQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senderLabel)
                    .addComponent(senderJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(receiverLabel)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(receiverJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierLabel)
                    .addComponent(supplierJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderLogTable;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel receiverJLabel;
    private javax.swing.JLabel receiverLabel;
    private javax.swing.JLabel senderJLabel;
    private javax.swing.JLabel senderLabel;
    private javax.swing.JLabel supplierJLabel;
    private javax.swing.JLabel supplierLabel;
    private javax.swing.JLabel trackLabel;
    private javax.swing.JLabel vaccineLabel;
    private javax.swing.JLabel vaccineNameLabel;
    private javax.swing.JLabel vaccineQuantityLabel;
    // End of variables declaration//GEN-END:variables
}
