/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClinicManager;

import Business.Inventory.InventoryDirectory;
import Business.Inventory.InventoryItem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HarshithaApurvaNikhitha
 */
public class ViewInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewInventoryJPanel
     */
    JPanel userProcessContainer;
    InventoryDirectory inventoryDirectory;
    public ViewInventoryJPanel(JPanel userProcessContainer, InventoryDirectory inventoryDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.inventoryDirectory = inventoryDirectory;
        populateJTable();
    }
    
    public void populateJTable(){
    
    DefaultTableModel model = (DefaultTableModel) clinicInventoryTable.getModel();
        
        model.setRowCount(0);
        int i =0;
        for (InventoryItem inventoryItem: inventoryDirectory.getInventoryList()){
            Object[] row = new Object[3];
            row[0] = ++i;
            row[1] = inventoryItem.getVaccine().getVaccineName();
            row[2] = inventoryItem.getQuantity();
                       
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inventoryLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clinicInventoryTable = new javax.swing.JTable();
        refreshTestBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        inventoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventoryLabel.setText("View Inventory");
        add(inventoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 580, 41));

        clinicInventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl No", "Vaccine Name", "Quantity Available"
            }
        ));
        jScrollPane1.setViewportView(clinicInventoryTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 600, 196));

        refreshTestBtn.setBackground(new java.awt.Color(153, 153, 153));
        refreshTestBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        refreshTestBtn.setText("Refresh Table");
        refreshTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestBtnActionPerformed(evt);
            }
        });
        add(refreshTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestBtnActionPerformed

        populateJTable();
    }//GEN-LAST:event_refreshTestBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable clinicInventoryTable;
    private javax.swing.JLabel inventoryLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestBtn;
    // End of variables declaration//GEN-END:variables
}
