/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CDCManager;

import Business.DiseaseList.Disease;
import Business.DiseaseList.DiseaseList;
import Business.VaccineDirectory.VaccineList;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * @author HarshithaApurvaNikhitha
 */
public class AddNewVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewVaccineJPanel
     */

    JPanel userProcessContainer;
    DiseaseList diseaseList;
    VaccineList vaccineList;

    public AddNewVaccineJPanel(JPanel userProcessContainer, DiseaseList diseaseList, VaccineList vaccineList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.diseaseList = diseaseList;
        this.vaccineList = vaccineList;
        populateComboBox();
    }

    private void populateComboBox() {
        diseasesCombo.removeAllItems();
        for (Disease disease : diseaseList.getDiseaseList()) {
            diseasesCombo.addItem(disease);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vaccineLabel = new javax.swing.JLabel();
        enterVaccineLabel = new javax.swing.JLabel();
        vaccineNameTxt = new javax.swing.JTextField();
        diseasesCombo = new javax.swing.JComboBox();
        diseaseLabel = new javax.swing.JLabel();
        addVaccineBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vaccineLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        vaccineLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vaccineLabel.setText("Add New Vaccine");
        add(vaccineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 561, 41));

        enterVaccineLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        enterVaccineLabel.setText("Enter Vaccine Name:");
        add(enterVaccineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 230, 50));

        vaccineNameTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(vaccineNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 230, 50));

        diseasesCombo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        diseasesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        add(diseasesCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 240, 50));

        diseaseLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        diseaseLabel.setText("Disease Combacted:");
        add(diseaseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 210, 40));

        addVaccineBtn.setBackground(new java.awt.Color(153, 153, 153));
        addVaccineBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addVaccineBtn.setText("Add Vaccine");
        addVaccineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccineBtnActionPerformed(evt);
            }
        });
        add(addVaccineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 170, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void addVaccineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccineBtnActionPerformed
        // TODO add your handling code here:
        String vaccineName = vaccineNameTxt.getText();
        Disease disease = (Disease) diseasesCombo.getSelectedItem();
        if (!vaccineName.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(null, "Vaccine name should contain only letters", "Info", JOptionPane.WARNING_MESSAGE);
            return;
        }

        vaccineList.addNewVaccine(vaccineName, disease);
        JOptionPane.showMessageDialog(null, "Vaccine added successfully");

    }//GEN-LAST:event_addVaccineBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccineBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel diseaseLabel;
    private javax.swing.JComboBox diseasesCombo;
    private javax.swing.JLabel enterVaccineLabel;
    private javax.swing.JLabel vaccineLabel;
    private javax.swing.JTextField vaccineNameTxt;
    // End of variables declaration//GEN-END:variables
}
