/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CDCManager;

import Business.DiseaseList.Disease;
import Business.DiseaseList.DiseaseList;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HarshithaApurvaNikhitha
 */
public class ManageDiseaseCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiseaseCatalogJPanel
     */
    JPanel userProcessContainer;
    DiseaseList diseaseList;
    
    public ManageDiseaseCatalogJPanel(JPanel userProcessContainer, DiseaseList diseaseList) {
        initComponents();
        this.diseaseList = diseaseList;
        this.userProcessContainer = userProcessContainer;
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) diseaseCatalogTable.getModel();
        
        model.setRowCount(0);
        
        int i = 0;
        for(Disease disease: diseaseList.getDiseaseList()){
            Object[] row = new Object[2];
            row[0] = ++i;
            row[1] = disease;
            model.addRow(row);
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        diseaseCatalogTable = new javax.swing.JTable();
        CatalogLabel = new javax.swing.JLabel();
        addNewDiseaseBtn = new javax.swing.JButton();
        removeDiseaseBtn = new javax.swing.JButton();
        diseaseNameTxt = new javax.swing.JTextField();
        DiseaseLabel = new javax.swing.JLabel();
        adddiseaseLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diseaseCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No", "Disease Name"
            }
        ));
        jScrollPane1.setViewportView(diseaseCatalogTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 106, 670, 179));

        CatalogLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CatalogLabel.setText("Disease Catalog");
        add(CatalogLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 70, 190, 30));

        addNewDiseaseBtn.setBackground(new java.awt.Color(153, 153, 153));
        addNewDiseaseBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addNewDiseaseBtn.setText("Add New Disease");
        addNewDiseaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDiseaseBtnActionPerformed(evt);
            }
        });
        add(addNewDiseaseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 210, 40));

        removeDiseaseBtn.setBackground(new java.awt.Color(153, 153, 153));
        removeDiseaseBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        removeDiseaseBtn.setText("Remove Disease");
        removeDiseaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDiseaseBtnActionPerformed(evt);
            }
        });
        add(removeDiseaseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 210, -1));
        add(diseaseNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 260, 40));

        DiseaseLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        DiseaseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiseaseLabel.setText("Manage Disease Catalog ");
        add(DiseaseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 580, 41));

        adddiseaseLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        adddiseaseLabel.setText("Add Disease:");
        add(adddiseaseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, 40));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void addNewDiseaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDiseaseBtnActionPerformed
        // TODO add your handling code here:
        String diseaseName = diseaseNameTxt.getText();
        diseaseList.addDisease(diseaseName);
        populateTable();
        
    }//GEN-LAST:event_addNewDiseaseBtnActionPerformed

    private void removeDiseaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDiseaseBtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = diseaseCatalogTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        Disease disease = (Disease) diseaseCatalogTable.getValueAt(selectedRow, 1);
        diseaseList.removeDisease(disease);
        populateTable();
        
    }//GEN-LAST:event_removeDiseaseBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CatalogLabel;
    private javax.swing.JLabel DiseaseLabel;
    private javax.swing.JButton addNewDiseaseBtn;
    private javax.swing.JLabel adddiseaseLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable diseaseCatalogTable;
    private javax.swing.JTextField diseaseNameTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeDiseaseBtn;
    // End of variables declaration//GEN-END:variables
}
