/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CDCManager;

import Business.DiseaseList.Disease;
import Business.DiseaseList.DiseaseList;
import Business.VaccineDirectory.Vaccine;
import Business.VaccineDirectory.VaccineList;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HarshithaApurvaNikhitha
 */
public class ManageVaccineCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccineCatalogJPanel
     */
    JPanel userProcessContainer;
    DiseaseList diseaseList;
    VaccineList vaccineList;
    
    public ManageVaccineCatalogJPanel(JPanel userProcessContainer, DiseaseList diseaseList, VaccineList vaccineList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.diseaseList = diseaseList;
        this.vaccineList = vaccineList;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) vaccineCatalogTable.getModel();
        
        model.setRowCount(0);
        
        int i = 0;
        for(Vaccine vaccine: vaccineList.getVaccineList()){
            Object[] row = new Object[3];
            row[0] = ++i;
            row[1] = vaccine;
            row[2] = vaccine.getDiseaseUsedFor();
            model.addRow(row);
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineCatalogTable = new javax.swing.JTable();
        catalogLabel = new javax.swing.JLabel();
        addNewVaccineBtn = new javax.swing.JButton();
        removeVaccineBtn = new javax.swing.JButton();
        vaccineCatalogLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vaccineCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No", "Vaccine Name", "Disease combacted"
            }
        ));
        jScrollPane1.setViewportView(vaccineCatalogTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 710, 178));

        catalogLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        catalogLabel.setText("Vaccine Catalog");
        add(catalogLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 79, 190, 30));

        addNewVaccineBtn.setBackground(new java.awt.Color(153, 153, 153));
        addNewVaccineBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addNewVaccineBtn.setText("Add New Vaccine");
        addNewVaccineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewVaccineBtnActionPerformed(evt);
            }
        });
        add(addNewVaccineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 311, 240, -1));

        removeVaccineBtn.setBackground(new java.awt.Color(153, 153, 153));
        removeVaccineBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        removeVaccineBtn.setText("Remove Vaccine");
        removeVaccineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeVaccineBtnActionPerformed(evt);
            }
        });
        add(removeVaccineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 210, -1));

        vaccineCatalogLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        vaccineCatalogLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vaccineCatalogLabel.setText("Manage Vaccine Catalog ");
        add(vaccineCatalogLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 580, 41));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 110, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void addNewVaccineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewVaccineBtnActionPerformed
        // TODO add your handling code here:
        AddNewVaccineJPanel addNewVaccineJPanel = new AddNewVaccineJPanel(userProcessContainer, diseaseList, vaccineList);
        userProcessContainer.add("manageOrganizationJPanel", addNewVaccineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_addNewVaccineBtnActionPerformed

    private void removeVaccineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeVaccineBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = vaccineCatalogTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        Disease disease = (Disease) vaccineCatalogTable.getValueAt(selectedRow, 1);
        diseaseList.removeDisease(disease);
        populateTable();

    }//GEN-LAST:event_removeVaccineBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewVaccineBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel catalogLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeVaccineBtn;
    private javax.swing.JLabel vaccineCatalogLabel;
    private javax.swing.JTable vaccineCatalogTable;
    // End of variables declaration//GEN-END:variables
}
