/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Analytics;

import Business.EcoSystem;
import Business.Enterprise.TravelAgencyEnterprise;
import Business.Order.OrderRequest;
import Business.Transport.TransportMode;
import java.awt.CardLayout;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HarshithaApurvaNikhitha
 */
public class count_of_amb extends javax.swing.JPanel {

    /**
     * Creates new form count_of_amb
     */
    EcoSystem ecoSystem;
    public count_of_amb(EcoSystem ecoSystem) {
        initComponents();
        this.ecoSystem = ecoSystem;
        populateTable();
    }

    public void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel)numberoftimesusedTable.getModel();
        int drone = 0;
        int ambulance = 0;
        for(TravelAgencyEnterprise travelAgency : ecoSystem.getAllTravelAgencyEnterprisesFromAllCountries()) {
            
            for( OrderRequest orderRequest:travelAgency.getOrderQueue().getOrderRequests() ){
                if(orderRequest.getTransportMode().equals(TransportMode.test.Drone)){
                    drone += 1;
                }
                else{
                    ambulance +=1;
                }
            }
        }

        Object[] row1 = new Object[2];
        row1[0] = "Drone";
        row1[1] = drone;
        model.addRow(row1);
        Object[] row2 = new Object[2];
        row2[0] = "Ambulance";
        row2[1] = ambulance;
        model.addRow(row2);    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        numberoftimesusedTable = new javax.swing.JTable();
        ambulanceLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberoftimesusedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mode of transport", "Number of times used"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(numberoftimesusedTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 97, -1, 295));

        ambulanceLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ambulanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ambulanceLabel.setText("Number of times Ambulance or Drone used");
        add(ambulanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 700, 41));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ambulanceLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable numberoftimesusedTable;
    // End of variables declaration//GEN-END:variables
}
