/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Analytics;

import Business.Enterprise.Hospital;
import Business.Network.StateNetwork;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * @author HarshithaApurvaNikhitha
 */
public class Max_Doc_Req extends javax.swing.JPanel {

    /**
     * Creates new form Max_Doc_Req
     */
    StateNetwork network;
    JPanel userProcessContainer;

    public Max_Doc_Req(JPanel userProcessContainer, StateNetwork network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) maxdocreqTable.getModel();

        model.setRowCount(0);

        for (Hospital hospital : network.getEnterpriseList().getHospitalEnterpriseList()) {
            if (hospital.getOrganizationList() != null) {
                for (Organization organization : hospital.getOrganizationList().getOrganizationList()) {
                    if (organization.getUserAccountList() != null) {
                        for (UserAccount userAccount : organization.getUserAccountList().getUserAccountList()) {

                            Object[] row = new Object[3];
                            row[0] = network.getNetworkName();
                            row[1] = userAccount.getEmployee().getEmployeeName();
                            row[2] = userAccount.getOrderQueue().getOrderRequests().size();


                            model.addRow(row);
                        }
                    }
                }
            }

        }


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        maxdocreqTable = new javax.swing.JTable();
        doctororderLabel = new javax.swing.JLabel();
        backBtn2 = new javax.swing.JButton();

        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maxdocreqTable.setAutoCreateRowSorter(true);
        maxdocreqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "State", "Doctor Name", "Number Of Requests"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(maxdocreqTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 107, 706, 185));

        doctororderLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        doctororderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctororderLabel.setText("Doctor order request counts");
        add(doctororderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 561, 41));

        backBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn2.setText("Back");
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });
        add(backBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton backBtn2;
    private javax.swing.JLabel doctororderLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable maxdocreqTable;
    // End of variables declaration//GEN-END:variables
}
