/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Analytics;

import Business.EcoSystem;
import Business.Enterprise.Hospital;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Order.OrderRequest;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * @author HarshithaApurvaNikhitha
 */
public class Time_Lapse extends javax.swing.JPanel {

    /**
     * Creates new form Time_Lapse
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;

    public Time_Lapse(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        timelapseTable = new javax.swing.JTable();
        timelapseLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timelapseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Disease", "Vaccine", "Request Date", "Resolve Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(timelapseTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 116, 862, 353));

        timelapseLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        timelapseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timelapseLabel.setText("Time lapse from Request to Delivery");
        add(timelapseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 561, 41));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdminRole/click-go-back-button.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) timelapseTable.getModel();

        model.setRowCount(0);
        int i = 0;
        for (CountryNetwork countryNetwork : ecoSystem.getCountryList()) {
            if (countryNetwork.getStateNetwork() != null) {
                for (StateNetwork stateNetwork : countryNetwork.getStateNetwork()) {
                    if (stateNetwork.getEnterpriseList() != null) {
                        for (Hospital hospital : stateNetwork.getEnterpriseList().getHospitalEnterpriseList()) {
                            if (hospital.getOrganizationList() != null) {
                                for (Organization organization : hospital.getOrganizationList().getOrganizationList()) {
                                    if (organization.getUserAccountList() != null) {
                                        for (UserAccount userAccount : organization.getUserAccountList().getUserAccountList()) {
                                            for (OrderRequest orderRequest : userAccount.getOrderQueue().getOrderRequests()) {
                                                Object[] row = new Object[5];
                                                row[0] = orderRequest.getOrderId();
                                                row[1] = orderRequest.getPatient().getDisease();
                                                row[2] = orderRequest.getVaccine();
                                                row[3] = orderRequest.getOrderRequestDate();
                                                row[4] = orderRequest.getOrderResolvedDate();


                                                model.addRow(row);
                                            }
                                        }
                                    }
                                }
                            }

                        }
                    }
                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel timelapseLabel;
    private javax.swing.JTable timelapseTable;
    // End of variables declaration//GEN-END:variables
}
